server:
  port: 10083

spring:
  application:
    name: base-eryi
  aop:
    proxy-target-class: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ab?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#swagger
swagger:
  title: eryi-API文档
  description: 这里是base-eryi系统
  terms-of-servic-url:
  contact:
    name: SwaggerName
    url:
    email: SwaggerEmail
  license: Apache License Version 2.0
  license-url:
  version: 1.0
